config/routes.rb
Rails.application.routes.draw do
  # root to #index action of global controller
  root 'home#index'

  # login (sessions) routes with named helpers
  get '/login' => 'sessions#new', as: 'login_form'
  post '/login' => 'sessions#create', as: 'login'
  delete '/logout' => 'sessions#destroy', as: 'logout'

  # user routes with named helpers (just #new and #create actions)
  get '/signup' => 'users#new', as: 'signup_form'
  post '/users' => 'users#create', as: 'signup'

  patch '/users/:user_id/projects/:id/wordcount' => 'projects#update_wordcount', as: 'update_wordcount'

  # nested users and projects resources
  resources :users do
    resources :projects
  end
end

app/views/shared/_error_flash.html.erb
<% if flash[:error] %>
  <%= flash[:error] %>
<% end %>

app/views/shared/_global_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "WriteNow", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <% if current_user.projects.any? %>
            <li><%= link_to "Current Project", root_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", user_path(current_user), class: 'dropLink' %></li>
              <li><%= link_to "Account Settings", edit_user_path(current_user), class: 'dropLink' %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", logout_path, method: :delete, class: 'dropLink' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Signup", signup_form_path %></li>
          <li><%= link_to "Login", login_form_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>