config/routes.rb
Rails.application.routes.draw do
  # root to #index action of global controller
  root 'home#index'

  # login (sessions) routes with named helpers
  get '/login' => 'sessions#new', as: 'login_form'
  post '/login' => 'sessions#create', as: 'login'
  delete '/logout' => 'sessions#destroy', as: 'logout'

  # user routes with named helpers (just #new and #create actions)
  get '/signup' => 'users#new', as: 'signup_form'
  post '/users' => 'users#create', as: 'signup'

  patch '/users/:user_id/projects/:id/wordcount' => 'projects#update_wordcount', as: 'update_wordcount'

  # nested users and projects resources
  resources :users do
    resources :projects
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :milestones
  validates :title, :wordcount_goal, :current_wordcount, presence: true
  validates :title, length: { in: 1..130 }
  validates :wordcount_goal, :current_wordcount, numericality: true
  validate :project_deadline_date_cannot_be_in_the_past

  validates :goal_time_limit,    presence: true, if: "goal_deadline_date.blank?"
  validates :goal_deadline_date, presence: true, if: "goal_time_limit.blank?"

  def project_deadline_date_cannot_be_in_the_past
    errors.add(:goal_deadline_date, "has to be in the future!") if goal_deadline_date && goal_deadline_date < Date.today
  end

  def calculate_pace_per_day
    (self.wordcount_goal - self.current_wordcount) / days_until_deadline
  end

  def calc_words_percent_completed
    100 - ( (self.wordcount_goal.to_f - self.current_wordcount.to_f) / self.wordcount_goal.to_f * 100)
  end

  def num_words_to_goal
    self.wordcount_goal - self.current_wordcount
  end

  def calculate_pace_per_hours
    (self.num_words_to_goal / hours_until_deadline).round(0)
  end

  def calculate_pace
    self.goal_time_limit ? self.calculate_pace_per_hours : self.calculate_pace_per_day
  end

  def time_until_deadline
    self.pace_unit == "day" ? self.days_until_deadline : self.hours_until_deadline
  end

  def days_until_deadline
    (self.goal_deadline_date - Date.today).round(0) if self.pace_unit == "day"
  end

  def hours_until_deadline
    limit = self.goal_time_limit
    hours_passed = TimeDifference.between(Time.parse(DateTime.now.to_s), self.created_at.to_time).in_hours
    (limit - hours_passed).round(2)
  end

  def pace_unit
    self.goal_time_limit ? "hour" : "day"
  end

  def check_goal_type
    self.goal_time_limit ? :hours : :days
  end

  def active_project(current_user)
    current_user.projects.last if current_user.projects.last.active
  end

  def time_start_to_finish
    self.pace_unit == "day" ? self.days_start_to_finish : self.goal_time_limit
  end

  def days_start_to_finish
    (self.goal_deadline_date - self.created_at.to_date).to_f
  end

  def set_inactive
    self.update(active: false)
  end

  def completed?
    self.wordcount_goal_reached? || self.goal_deadline_reached?
  end

  def time_to_completion
    self.pace_unit == "day" ? self.days_to_completion : self.hours_to_completion
  end

  def days_to_completion
    (Date.today - self.created_at.to_date).to_f
  end

  def hours_to_completion
    (self.days_to_completion / 60).to_f
  end

  def wordcount_goal_reached?
    self.wordcount_goal <= self.current_wordcount
  end

  def goal_deadline_reached?
    self.time_expired? || self.date_arrived?
  end

  def time_expired?
    self.hours_until_deadline <= 0 if self.pace_unit == "hour"
  end

  def date_arrived?
    self.days_until_deadline <= 0 if self.pace_unit == "day"
  end

  def successful_completion?
    self.wordcount_goal_reached?
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :load_user

  def new
    @project = Project.new
  end

  def create
    @project = @user.projects.build(project_params)

    if @project.save
      if @user.projects.count == 1
        @user.badges.build(badge_name: "First Project Created!", award_trigger: "project1 #create success")
        @user.save
      end
      redirect_to root_path
    else
      flash.now[:error] = "Learn how to type ... if you want to be a writer."
      render 'projects/_new'
    end
  end

  def edit
    @project = @user.projects.last
    @goal_field = @project.check_goal_type
    render partial: 'projects/edit'
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes(project_params)
    @pace_needed = @project.calculate_pace
    @words_left = @project.num_words_to_goal
    @time_left = @project.time_until_deadline
    @pace_needed = @project.calculate_pace.floor
    @percent_complete = @project.calc_words_percent_completed.round(0)
    @pace_unit = @project.pace_unit
    redirect_to root_path
  end

  def update_wordcount
    @project = Project.find(params[:id])
    @project.update_attributes(project_params)

    @milestones = @project.milestones.create!(wordcount: project_params[:current_wordcount])
    @all_miles = @project.milestones
    
    count_holder = [0]
    time_holder = [0]
    @all_miles.each do |m_stone|
      count_holder << m_stone.wordcount
      time_holder << m_stone.created_at
    end

    @y_axis_wordcount_goal = @project.wordcount_goal

    @words_left = @project.num_words_to_goal
    @time_left = @project.time_until_deadline
    @pace_needed = @project.calculate_pace.floor
    @percent_complete = @project.calc_words_percent_completed.round(0)
    render json: [@words_left, @time_left, @pace_needed, @percent_complete, count_holder, time_holder, @y_axis_wordcount_goal]
  end

  def destroy
    @project = current_user.projects.last
    @project.destroy
    redirect_to root_path
  end

  private
  def project_params
    params.require(:project).permit(:title, :wordcount_goal, :goal_time_limit, :goal_deadline_date, :user_id, :current_wordcount)
  end

  def load_user
    @user = current_user
  end
end

app/views/projects/_completed_project.html.erb
<div class="completed_project">
  <h1>Your writing project <strong><em><%= @project.title.titleize %></em></strong> is over!</h1>

  <div class="project_message">
    <% if @successful %>
      <h2>Great job achieving your goals!</h2>

      <%= link_to "create another project", root_path %>

    <% else %>
      <h2>Try harder next time, lazy ass</h2>

      <%= link_to "create another project", root_path %>

    <% end %>
  </div>
</div>

app/views/projects/_current_project.html.erb
<div class="container-fluid currentProject">
  <div class="row">
    <h1><%= @project.title %> <span style='font-size:10pt;'>[current project]</span></h1>
    <hr class='projectDivider' />
  </div>
  <div class="row">
    <div class="col-md-6">
      <h3>Goal Wordcount</h3>
      <p class="goalWordcount"><%= @project.wordcount_goal %></p>
    </div>
    <div class="col-md-5">
      <h3>Words Left</h3>
      <p class="wordsLeft"><%= @words_left %></p>
    </div>
  </div>
  <div class="row">
    <h4>Your Goal Progress!</h4>
    <div class="progress col-md-12">
      <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="100" style="width: <%= @percent_complete %>%; background-color: #18506E; color: #EBA500;">
        <span id='percentComplete'><%= @percent_complete.round(0) %> %</span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <h3><%= @pace_unit.capitalize%>s Left</h3>
      <p class="timeLeft"><%= @time_left %></p>
    </div>
    <div class="col-md-4">
      <h3>Pace Needed</h3>
      <p class="paceNeeded"><%= @pace_needed %> <span style='font-size: 10pt;'>words per <%= @pace_unit %></span></p>
    </div>
    <div class="col-md-5">
      <h3>Update Wordcount</h3>
      <%= render partial: 'projects/new_current_wordcount' %>
    </div>
  </div>
  <div class="project_links">
  <hr class='projectDivider' />
    <%= link_to "Edit Project", edit_user_project_path(:user_id => current_user.id, :id => @project.id), id: 'editProjectForm', remote: true %>
    <span> | </span>
    <%= link_to "Delete Project", user_project_path(:user_id => current_user.id, :id => @project.id), :method => :delete %>
  </div>
</div>

app/views/projects/_days.html.erb
<div class="form-group">
  <div class="input-group">
    <%= f.label :goal_deadline_date, "Goal Deadline Date" %>
    <%= f.date_field :goal_deadline_date, class: 'form-control', placeholder: 'title' %>
  </div>
</div>

app/views/projects/_edit.html.erb
<div class='editProjectForm'>
  <h3>Edit your Project!</h3>
  <%= form_for [@user, @project], url: user_project_path(@user, @project), method: :patch, html: { id: 'updateProject', class: 'form-inline', role: 'form' } do |f| %>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: 'form-control', placeholder: 'title' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.label :wordcount_goal, "Wordcount Goal" %>
      <%= f.text_field :wordcount_goal, class: 'form-control', placeholder: 'wordcount goal' %>
    </div>
  </div>

  <% if @goal_field == :days %>
  <%=  render partial: 'days', locals: { f: f } %>
  <% else %>
  <%=  render partial: 'hours', locals: { f: f } %>
  <% end %>

  <%= f.submit "Edit Project!", class: 'btn btn-default' %>
  <% end %>
</div>

app/views/projects/_hours.html.erb
<div class="form-group">
  <div class="input-group">
    <%= f.label :goal_time_limit, "Goal Time Limit" %>
    <%= f.text_field :goal_time_limit, class: 'form-control', placeholder: 'title' %>
  </div>
</div>

app/views/projects/_new.html.erb
<div class="new-project">
  <h1>Create a new project!</h1>
  <%= form_for [@user, @project], html: { class: 'form-inline', role: 'form' } do |f| %>
  <div class="form-group">
    <div class="input-group">
      <%= f.text_field :title, class: 'form-control', placeholder: 'title' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <%= f.text_field :wordcount_goal, class: 'form-control', placeholder: 'wordcount goal' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <div class="unitToggle">
        <button class="toggleDeadlineUnitHours btn btn-default">Hours till Deadline</button>
        <span>or</span>
        <button class="toggleDeadlineUnitDate btn btn-default">Deadline Date</button>
      </div>
    </div>
  </div>
  <br />
  <%= f.submit "Create Project!", class: 'btn btn-default create-project' %>
  <% end %>

  <script type="text/javascript">
    $('.toggleDeadlineUnitDate').on('click', function(e) {
      e.preventDefault();
      $(this).parent().replaceWith("<input type='date' name='project[goal_deadline_date]' id='project_goal_deadline_date' class='form-control'></input>");
      $('.toggleDeadlineUnitHours').remove();
    });

    $('.toggleDeadlineUnitHours').on('click', function(e) {
      e.preventDefault();
      $(this).parent().replaceWith("<input type='text' name='project[goal_time_limit]' id='project_goal_time_limit' class='form-control' placeholder='hours till deadline'></input>");
      $('.toggleDeadlineUnitDate').remove();
    });
  </script>
</div>

app/views/projects/_new_current_wordcount.html.erb
<div class="updateWordCount">
  <%= form_for [@user, @project], remote: true, url: update_wordcount_path(@user, @project), html: { id: 'updateWordCount', class: 'form-inline', role: 'form' } do |f| %>
  <%= f.text_field :current_wordcount, class: 'form-control', placeholder: 'current wordcount' %>

  <%= f.submit "Update wordcount", class: 'updateCurrentWordcount btn btn-default' %>

  <% end %>
</div>

app/views/projects/_success_completed_project.html.erb
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="100" style="width: <%= @percent_complete %>%">
    <%= @project.wordcount_goal - @words_left %>
  </div>
</div>

<h3>You wrote <%= @project.wordcount_goal %> words in <%= @time_to_completion %> <%= @pace_unit%>s.</h3>

<h4>Create another project</h4>
<%= render partial: "projects/new" %>

app/views/projects/edit.html.erb
<%= form_for [@user, @project], url: user_project_path(@user, @project), method: :patch do |f| %>

  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>

  <%= f.label :wordcount_goal, "Wordcount Goal" %>
  <%= f.text_field :wordcount_goal %>

  <% if @goal_field == :days %>
    <%=  render partial: 'days', locals: { f: f } %>
  <% else %>
    <%=  render partial: 'hours', locals: { f: f } %>
  <% end %>

  <%= f.submit "Edit Project!" %>
<% end %>